export enum Topic {
  ChangedInscriptionState = 'student-inscription.changed-inscription-state',
  CommittedInscription = 'student-inscription.committed-inscription',
  GotClassDayInfo = 'student-inscription.got-class-day-info',
  GotClassDays = 'student-inscription.got-class-days',
  GotGroupInfo = 'student-inscription.got-group-info',
  GotGroups = 'student-inscription.got-groups',
  GotInscriptionInfo = 'student-inscription.got-inscription-info',
  GotInscriptions = 'student-inscription.got-inscriptions',
  GotSemesterInfo = 'student-inscription.got-semester-info',
  GotStudentInfo = 'student-inscription.got-student-info',
  MatchedClassDayData = 'student-inscription.matched-class-data',
  MatchedGroupData = 'student-inscription.matched-group-data',
  MatchedSemesterData = 'student-inscription.matched-semester-data',
  MatchedStudentData = 'student-inscription.matched-student-data',
  SubscribedGroup = 'student-inscription.subscribed-group',
  UnsubscribedGroup = 'student-inscription.unsubscribed-group',
}
